language: node_js
before_install:
  - npm install -g coffee-script mocha mocha-lcov-reporter blanket
before_script:
  - coffee -o ./lib -c -b ./src
node_js:
  - "0.10"
script:
  - npm test
after_success:
  - npm run-script test-coveralls
notifications:
  slack:
    masuilab:hVUieBVtngcw7Cf4lTqld2fj
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=7Gbts3oNP0nqyrJP8oQiBfSCaknO5Vret
